### ISSUE TITLE
ckan plugin-info crashes if doi is installed

### ISSUE THREAD

**Issue by andmar8** [NaturalHistoryMuseum/ckanext-doi#19]
Hello,

If I install this doi plugin using "python setup.py install" all seems to go through correctly.

If I run "ckan" I get a listing of all commands including the "doi" ckan command

If I run "ckan plugin-info" I get the following error:

```
doi:
----

    CKAN DOI Extension

Implements:
    IConfigurer
    IPackageController
    IConfigurable
Traceback (most recent call last):
  File "/usr/bin/ckan", line 45, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1326, in command
    self.get_info()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1361, in get_info
    extra = self.template_helpers(p['class'])
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1378, in template_helpers
    return self.function_info(helpers)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1386, in function_info
    args_info = inspect.getargspec(fn)
  File "/usr/lib/python2.7/inspect.py", line 815, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <built-in method now of type object at 0x7f1ecaaa2c40> is not a Python function
```

What am I doing wrong??

**Comment by andmar8** [comment]
My hunch is there's "something" wrong with the entry points declaration in the setup.py... but my background is not python so I'm struggling a little.

**Comment by andmar8** [comment]
```
from setuptools import setup, find_packages

version = '0.2'

setup(
        name='ckanext-doi',
        version=version,
        description='CKAN extension for assigning a DOI to datasets',
        classifiers=[],
        keywords='',
        author='Ben Scott',
        author_email='ben@benscott.co.uk',
        url='',
        license='',
        packages=find_packages(exclude=['tests']),
        namespace_packages=['ckanext', 'ckanext.doi'],
        include_package_data=True,
        zip_safe=False,
        install_requires=[],
        entry_points=\
        """
    [ckan.plugins]
        doi=ckanext.doi.plugin:DOIPlugin

    [paste.paster_command]
        doi=ckanext.doi.commands.doi:DOICommand
        """,
)
```

**Comment by benscott** [comment]
Let me look into it...what version of CKAN are you running?

**Comment by andmar8** [comment]
I believe it was installed from: "python-ckan_2.3_amd64.deb", so presumably 2.3

ckan --version returns: PasteScript 1.7.5 from /usr/lib/ckan/default/lib/python2.7/site-packages (python 2.7.3 (default, Dec 18 2014, 19:10:20))

**Comment by benscott** [comment]
Sorry, there was a bug - now fixed. If you do a pull ckan plugin-info should now be working.

**Comment by andmar8** [comment]
Ran a git pull:
'''
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 17 (delta 1), reused 0 (delta 0), pack-reused 9
Unpacking objects: 100% (17/17), done.
From https://github.com/NaturalHistoryMuseum/ckanext-doi
   c9c02e3..39c0eda  master     -> origin/master
Updating c9c02e3..39c0eda
Fast-forward
 README.md              |   11 ++++++++++-
 ckanext/doi/helpers.py |    4 ++++
 ckanext/doi/plugin.py  |    5 ++---
 3 files changed, 16 insertions(+), 4 deletions(-)
'''
Tried a build and install:
'''
python setup.py build
python setup.py install
'''
Ran "ckan", fine doi plugin there, ran "ckan doi --help", fine plugin working, ran "ckan plugin-info", same error:
'''
doi:
----

    CKAN DOI Extension

Implements:
    IConfigurer
    IPackageController
    IConfigurable
Traceback (most recent call last):
  File "/usr/bin/ckan", line 45, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1326, in command
    self.get_info()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1361, in get_info
    extra = self.template_helpers(p['class'])
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1378, in template_helpers
    return self.function_info(helpers)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1386, in function_info
    args_info = inspect.getargspec(fn)
  File "/usr/lib/python2.7/inspect.py", line 815, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <built-in method now of type object at 0x7fcc56cf7c40> is not a Python function
'''
Tried a service restart:
'''
service apache2 restart
service nginx restart
'''
Tried "ckan plugin-info", still no joy :(

I'm gonna see if I can uninstall the plugin then reinstall... somehow, I'll update this if I manage

**Comment by benscott** [comment]
I've updated the namespaces and tweaked my fix yesterday...could you try again please?

**Comment by andmar8** [comment]
I "hope" I've done this right...

```
git pull
python setup.py build
python setup.py install
service apache2 restart
service nginx restart
ckan #works fine
ckan doi #works fine
ckan plugin-info #works fine
```
So basically I did not uninstall anything, just install again.
On the command line all looks to be working (so I guess we could close this issue), but I'm still not seeing much happening when I create a new dataset in the webapp. How do I know the plugin has worked?... would you like me to open another issue?

**Comment by benscott** [comment]
Great, glad that's sorted the errors.

After creating a new dataset, you should see a "Cite this dataset" block on the dataset page. If that's not showing up, yep please raise as another issue and I'll look into that now.
